language: ruby
rvm:
 - "1.8.7"
 - "1.9.2"
 - "1.9.3"
 - rbx
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
notifications:
  slack: syamaraj:ywdICIRgFgxdwBUHT2yjcFPn
  webhooks: 
    - http://requestb.in/1amq9yz1
    - http://11ff8410.ngrok.io/webhook/87901511-7fa0-4de7-af34-51920e5c9d4b@fc3b327b-ed86-4d39-a9d7-6c87bfe89795/TravisCI/6133209d51544705b40cfac915feb931?GroupOwner=admin@tenant-EXHV-3704.COM
